language: c
sudo: required
services:
  - docker

matrix:
  include:
    - env:
        - BLAS=openblas
        - PY_VER=2.7
    - env:
        - BLAS=openblas
        - PY_VER=3.4
    - env:
        - BLAS=openblas
        - PY_VER=3.5
    - env:
        - BLAS=atlas
        - PY_VER=2.7
    - env:
        - BLAS=atlas
        - PY_VER=3.4
    - env:
        - BLAS=atlas
        - PY_VER=3.5

script:
  - docker run -ti --rm -e BLAS_SOURCE=$BLAS -e PYTHON_VERSIONS=$PY_VER -v $PWD:/io quay.io/pypa/manylinux1_x86_64 /io/build_stack.sh
