sudo: required
language: python
services:
  - docker
install:
    - docker pull quay.io/pypa/manylinux1_x86_64
script:
    - docker run --rm -v $PWD:/io quay.io/pypa/manylinux1_x86_64 /io/build_hdf5s.sh
    - ls libraries

